server:
  port: 8080
spring:
  application:
    name: "Autenticacion"
  devtools:
    add-properties: false
  webflux:
    base-path: /api
  h2:
    console:
      enabled: true
      path: "/h2"
  profiles:
    include: null
adapters:
  r2dbc:
    host: ${R2DBC_HOST_AUTH:localhost}
    port: ${R2DBC_PORT_AUTH:5432}
    database: ${R2DBC_DATABASE_AUTH:pragma}
    schema: ${R2DBC_SCHEMA_AUTH:public}
    username: ${R2DBC_USERNAME_AUTH:postgres}
    password: ${R2DBC_PASSWORD_AUTH:1234}
security:
  jwt:
    secretkey: ${JWT_SECRET_KEY:Bardelhaus1234567890Bardelhaus1234567890$}
    expiration: ${JWT_SECRET_KEY_EXPIRATION:3600000}
management:
  endpoints:
    web:
      exposure:
        include: "health,prometheus"
  endpoint:
    health:
      probes:
        enabled: true
cors:
  allowed-origins: "http://localhost:4200,http://localhost:8080"
