CREATE EXTENSION IF NOT EXISTS pgcrypto;

CREATE TABLE public.rol (
	id UUID DEFAULT gen_random_uuid(),
	nombre varchar(255) NOT NULL,
	descripcion varchar(255) NOT NULL,
	CONSTRAINT rol_pk PRIMARY KEY (id)
);

CREATE TABLE public.usuario (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	nombres varchar(255) NOT NULL,
	apellidos varchar(255) NOT NULL,
	documento_identidad varchar(50) NOT NULL,
	fecha_nacimiento date NULL,
	salario_base numeric(10, 2) NOT NULL,
	email varchar(50) NOT NULL,
	telefono varchar(50) NULL,
	direccion varchar(100) NULL,
	id_rol UUID null,
	contrasena varchar(255) NULL,
	CONSTRAINT usuario_pk PRIMARY KEY (id),
	CONSTRAINT usuario_rol_fk FOREIGN KEY (id_rol) REFERENCES public.rol(id)
);

INSERT INTO rol (id, nombre, descripcion) VALUES('74ab91d6-cae8-46a8-a59c-6f0f64d074cc'::uuid, 'ADMIN', 'Rol con privilegios completos para la gestión del sistema');
INSERT INTO rol (id, nombre, descripcion) VALUES('ef4ae4c7-5ac5-450e-b21d-915273949422'::uuid, 'ASESOR', 'Rol encargado de asesorar y gestionar solicitudes de usuarios');
INSERT INTO rol (id, nombre, descripcion) VALUES('dd6db27a-6d9e-418b-a0f0-82a88697995e'::uuid, 'CLIENTE', 'Rol correspondiente a los usuarios finales que realizan solicitudes');

ALTER TABLE public.usuario
ADD COLUMN password_hash VARCHAR(255) NULL;

INSERT INTO usuario (id, nombres, apellidos, documento_identidad, fecha_nacimiento, salario_base, email, telefono, direccion, id_rol, contrasena) VALUES(17, 'Rocio', 'Pabon', '21176489', '1966-05-04', 5000000.00, 'rociopabon1@gmail.com', '1111111112', 'cll 6 sur', 'dd6db27a-6d9e-418b-a0f0-82a88697995e'::uuid, '$2a$12$pW/8VsSQYduH/6xEDhnMqOuNg8O7jYOWG0i3tR5mIbSarY2cBiYdy');
INSERT INTO usuario (id, nombres, apellidos, documento_identidad, fecha_nacimiento, salario_base, email, telefono, direccion, id_rol, contrasena) VALUES(18, 'Andres', 'Pereira', '79288455', '1963-05-04', 5000000.00, 'andrespereira@gmail.com', '1111111112', 'cll 6 sur', 'ef4ae4c7-5ac5-450e-b21d-915273949422'::uuid, '$2a$12$L6PGgkS0ImzOvXgqaySMPenrY7tP67Oezyyzkr0WxBp2a6gqUXeQ2');
INSERT INTO usuario (id, nombres, apellidos, documento_identidad, fecha_nacimiento, salario_base, email, telefono, direccion, id_rol, contrasena) VALUES(1, 'natalia', 'barbosa', '1122133216', '1993-05-01', 5000000.00, 'jandreaj100@gmail.com', NULL, NULL, '74ab91d6-cae8-46a8-a59c-6f0f64d074cc'::uuid, '$2a$12$FSULkXpT.1OFnLsZolmtn.e62NSFRTAv4MixPbvCht0XnR0xYJGaK');