CREATE EXTENSION IF NOT EXISTS pgcrypto;

CREATE TABLE rol (
	id UUID DEFAULT gen_random_uuid(),
	nombre varchar(255) NOT NULL,
	descripcion varchar(255) NOT NULL,
	CONSTRAINT rol_pk PRIMARY KEY (id)
);

CREATE TABLE usuario (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	nombres varchar(255) NOT NULL,
	apellidos varchar(255) NOT NULL,
	documento_identidad varchar(50) NOT NULL,
	fecha_nacimiento date NULL,
	salario_base numeric(10, 2) NOT NULL,
	email varchar(50) NOT NULL,
	telefono varchar(50) NULL,
	direccion varchar(100) NULL,
	id_rol UUID null,
	CONSTRAINT usuario_pk PRIMARY KEY (id),
	CONSTRAINT usuario_rol_fk FOREIGN KEY (id_rol) REFERENCES public.rol(id)
);

ALTER TABLE public.usuario
ADD CONSTRAINT usuario_rol_fk
FOREIGN KEY (id_rol)
REFERENCES public.rol (id);

INSERT INTO public.rol (nombre, descripcion)
VALUES
  ('ADMIN', 'Rol con privilegios completos para la gestión del sistema'),
  ('ASESOR', 'Rol encargado de asesorar y gestionar solicitudes de usuarios'),
  ('CLIENTE', 'Rol correspondiente a los usuarios finales que realizan solicitudes');

ALTER TABLE public.usuario
ADD COLUMN password_hash VARCHAR(255) NULL;