CREATE TABLE public.usuario (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	nombres varchar(255) NOT NULL,
	apellidos varchar(255) NOT NULL,
	documento_identidad varchar(50) NOT NULL,
	fecha_nacimiento date NULL,
	salario_base numeric(10,2) not null,
	email varchar(50) NOT NULL,
	telefono varchar(50) NULL,
	direccion varchar(100) NULL,
	constraint usuario_pk primary key (id)
);